//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJsAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id { get; set; }
        public string Fullname { get; set; }
        public string Telephone { get; set; }
        public string Model { get; set; }
        public string Manufacture { get; set; }
        public int Registration { get; set; }
    }
}
